/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchesRouteImport } from './routes/watches'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as PerfumesRouteImport } from './routes/perfumes'
import { Route as GiftsRouteImport } from './routes/gifts'
import { Route as BooksRouteImport } from './routes/books'
import { Route as IndexRouteImport } from './routes/index'

const WatchesRoute = WatchesRouteImport.update({
  id: '/watches',
  path: '/watches',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfumesRoute = PerfumesRouteImport.update({
  id: '/perfumes',
  path: '/perfumes',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftsRoute = GiftsRouteImport.update({
  id: '/gifts',
  path: '/gifts',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/gifts': typeof GiftsRoute
  '/perfumes': typeof PerfumesRoute
  '/shipping': typeof ShippingRoute
  '/watches': typeof WatchesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/gifts': typeof GiftsRoute
  '/perfumes': typeof PerfumesRoute
  '/shipping': typeof ShippingRoute
  '/watches': typeof WatchesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/gifts': typeof GiftsRoute
  '/perfumes': typeof PerfumesRoute
  '/shipping': typeof ShippingRoute
  '/watches': typeof WatchesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/books' | '/gifts' | '/perfumes' | '/shipping' | '/watches'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/books' | '/gifts' | '/perfumes' | '/shipping' | '/watches'
  id:
    | '__root__'
    | '/'
    | '/books'
    | '/gifts'
    | '/perfumes'
    | '/shipping'
    | '/watches'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksRoute: typeof BooksRoute
  GiftsRoute: typeof GiftsRoute
  PerfumesRoute: typeof PerfumesRoute
  ShippingRoute: typeof ShippingRoute
  WatchesRoute: typeof WatchesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watches': {
      id: '/watches'
      path: '/watches'
      fullPath: '/watches'
      preLoaderRoute: typeof WatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfumes': {
      id: '/perfumes'
      path: '/perfumes'
      fullPath: '/perfumes'
      preLoaderRoute: typeof PerfumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gifts': {
      id: '/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof GiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksRoute: BooksRoute,
  GiftsRoute: GiftsRoute,
  PerfumesRoute: PerfumesRoute,
  ShippingRoute: ShippingRoute,
  WatchesRoute: WatchesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
